version: '3'

services:
    notification-service-processing:
        container_name: notification-service-processing
        image: docker.your-company.com/notification-service-processing:latest
        environment:
        - OSDR_LOG_FOLDER=/logs
        - OSDR_MONGO_DB=mongodb://mongo:27017/osdr
        - OSDR_RABBIT_MQ=rabbitmq://guest:guest@rabbitmq:5672/osdr_dev
        volumes:
        - ${OSDR_LOG_FOLDER}:/logs/
        networks:
        - osdr-net-ext

networks:
    osdr-net-ext:
        external:
            name: osdr-sys-net
